[package]
name = "rusty-warrior"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
legion = "0.4.0"
serde = "=1.0.133"
ron = "=0.7.0"